name: Node.js CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'  # También puedes usar 'zulu' o 'adopt'

    - name: Clean npm cache
      run: npm cache clean --force

    - name: Remove node_modules
      run: rm -rf node_modules

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npx jest --passWithNoTests

    - name: Build Android project
      run: ./gradlew build
